name: chaechoicpa
favicon: null
layout_spectrum: 0.87396
typography_spectrum: 0.32468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f7df9'
    - '#060584'
    - '#b6b5db'
    - '#fa8b2a'
  brandStrength: 0.625
  lightness: 0.6244870161172003
  saturation: 0.3818487995304167
  rhythmicContrast: 0.4622092773206532
purpose: []
