name: chaechoicpa
favicon: null
layout_spectrum: 0.99404
typography_spectrum: 0.63823
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Welcome to Chae Choi, CPA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161E1F'
    - '#EAFBF1'
    - '#EAADBC'
    - '#30A391'
    - '#E9BD6E'
  brandStrength: 1
  lightness: 0.4914071
  saturation: 0.5204082
  rhythmicContrast: 0.5870032
purpose: []
