name: chaechoicpa
favicon: null
layout_spectrum: 0.7330784290097654
typography_spectrum: 0.7954799002036452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8494826266542077
  lightness: 0.6244870161172003
  saturation: 0.3818487995304167
  rhythmicContrast: 0.4622092773206532
purpose: []
