title: 'Welcome to Chae Choi, CPA'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7105263
  brandStrength: 0.75
  lightness: 0.7212675
  brandColors:
    - '#23282B'
    - '#FFBBC5'
    - '#FFFF8F'
    - '#3AB29B'
    - '#FF8359'
  rhythmicContrast: 0.6922663
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: chaechoicpa
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1734694
layout_spectrum: 0.8888292
